version: "2"

services:
  mosquitto:
    image: gyengus/alpine-mosquitto
    restart: always
    hostname: mqtt
    volumes:
      - ./conf:/conf
      - ./logs:/var/log
    ports:
    - "1883:1883"
    - "1884:1884"
